### ISSUE TITLE
Don't include the sources when publishing the package

### ISSUE THREAD

**Issue by aminnairi** [Alexandrebdry/react-mui-snackbar#1]
Source files are unecessary when publishing the package.

However, they are included in the package that gets downloaded when running `npm install react-mui-snackbar`.

The package should probably use the `files` property for the [`package.json`](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#files) file to prevent including other unecessary files.

**Comment by Alexandrebdry** [comment]
Thanks. It has been done on files branch https://github.com/Alexandrebdry/react-mui-snackbar/tree/files
