### ISSUE TITLE
Linter

### ISSUE THREAD

**Issue by aminnairi** [Alexandrebdry/react-mui-snackbar#11]
This would be great if this library use a linter to check for code style issues such as inconsistent indentation of missing semi-colon so that the source-code is easier to read for someone that wants to know more about this library or for people wanting to contribute to this project.

A continuous integration unit test alongside these linter tests would help automate the process.

Using [ESLint](https://eslint.org/) would be the best choice in my opinion.

**Comment by Alexandrebdry** [comment]
Done
