### ISSUE TITLE
useSnackbarContext

### ISSUE THREAD

**Issue by aminnairi** [Alexandrebdry/react-mui-snackbar#13]
It would be great to avoid using the `SnackbarContext` directly and instead provide another layer of abstraction with an exposed function that would do the heavy lifting of using the `SnackbarContext` for us. This would provide a cleaner API that way.

```javascript
import { useSnackbarContext } from "react-mui-snackbar"

export const MyComponent = () => {
  // No more importing useContext from react
  // No more importing SnackbarContext directly from react-mui-snackbar
  const { openSnacbkar } = useSnackbarContext()
   
  // The rest of the component here...
}
```

**Comment by Alexandrebdry** [comment]
Thanks!
