### ISSUE TITLE
`useCallback` for `openSnackbar`

### ISSUE THREAD

**Issue by aminnairi** [Alexandrebdry/react-mui-snackbar#16]
Since the code for the definition of the `openSnackbar` might be the same from one rendering to another, and the `SnackbarContextProvider` component might live as a child of another component (most likely another provider), it can imply uncessary re-rendering that can cause the `openSnackbar` function to be redefined without any changes, introducing performance bottlenecks. 

It can help to use the `useCallback` hooks for defining the function `openSnackbar` so that this one don't get re-defined across multiple re-rendering of the provider hosting this function.

**Comment by Alexandrebdry** [comment]
Thanks for that advice. This feature has been done!
