### ISSUE TITLE
Open the snackbar for a given duration

### ISSUE THREAD

**Issue by aminnairi** [Alexandrebdry/react-mui-snackbar#2]
It would be great to be able to open the snackbar with a given duration as it is possible for the `Snackbar` component.

```jsx
openSnackbar("Hello", "success", 5000)
```

**Comment by Alexandrebdry** [comment]
That is a good idea! Thanks 👍 
it has been done on [duration branch](https://github.com/Alexandrebdry/react-mui-snackbar/tree/duration)
