### ISSUE TITLE
TypeScript

### ISSUE THREAD

**Issue by aminnairi** [Alexandrebdry/react-mui-snackbar#7]
It would be great to use TypeScript since it is very common to find packages that uses this language nowaday on NPM and provide many benefit for the developer experience.

Adding a property `"types": "build/index.d.ts"` (even if the project is not totally rewritten in TypeScript) would also be great in the `package.json` so that even when compiled to JavaScript, users still have the TypeScript definition types that can be triggered from VSCode Intellisense and help them better grasp the usage of this library.

**Comment by Alexandrebdry** [comment]
Close with latest version (V3.0.0)
